services:
  rest:
    restart: unless-stopped
    image: andytakker/insperia-lms-backend:latest
    entrypoint: python -m lms.presentation.rest
    ports:
      - 8000:80
    environment:
      APP_HTTP_HOST: ${APP_HTTP_HOST}
      APP_HTTP_PORT: ${APP_HTTP_PORT}
      APP_HTTP_TITLE: ${APP_HTTP_TITLE}
      APP_HTTP_DESCRIPTION: ${APP_HTTP_DESCRIPTION}
      APP_HTTP_VERSION: ${APP_HTTP_VERSION}

      APP_LOG_FORMAT: ${APP_LOG_FORMAT}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}

      APP_SECURITY_SECRET_KEY: ${APP_SECURITY_SECRET_KEY}

      APP_DATABASE_DSN: ${APP_DATABASE_DSN}

      APP_TELEGRAM_BOT_TOKEN: ${APP_TELEGRAM_BOT_TOKEN}
      APP_TELEGRAM_CHAT_ID: ${APP_TELEGRAM_CHAT_ID}

      APP_SOHO_API_TOKEN: ${APP_SOHO_API_TOKEN}

      APP_GOOGLE_KEYS: ${APP_GOOGLE_KEYS}

  cron:
    restart: unless-stopped
    image: andytakker/insperia-lms-backend:latest
    entrypoint: python -m lms.presentation.cron

    environment:
      APP_DATABASE_DSN: ${APP_DATABASE_DSN}

      APP_GOOGLE_KEYS: ${APP_GOOGLE_KEYS}

      APP_AUTOPILOT_REGULAR_NOTIFICATION_URL: ${APP_AUTOPILOT_REGULAR_NOTIFICATION_URL}
      APP_AUTOPILOT_SUBSCRIPTION_NOTIFICATION_URL: ${APP_AUTOPILOT_SUBSCRIPTION_NOTIFICATION_URL}
      APP_AUTOPILOT_ADDITIONAL_NOTIFICATION_URL: ${APP_AUTOPILOT_ADDITIONAL_NOTIFICATION_URL}

      APP_CRON_SCHEDULER: ${APP_CRON_SCHEDULER}

      APP_LOG_FORMAT: ${APP_LOG_FORMAT}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}

networks:
  default:
    external: true
    name: academy

